
package test;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "employeeLookupService", targetNamespace = "http://www.memorylack.com/company", wsdlLocation = "file:/home/thej/Desktop/webserviceServices/topdownsample/wsdl/company.wsdl")
public class EmployeeLookupService_Service
    extends Service
{

    private final static URL EMPLOYEELOOKUPSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEELOOKUPSERVICE_EXCEPTION;
    private final static QName EMPLOYEELOOKUPSERVICE_QNAME = new QName("http://www.memorylack.com/company", "employeeLookupService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/thej/Desktop/webserviceServices/topdownsample/wsdl/company.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEELOOKUPSERVICE_WSDL_LOCATION = url;
        EMPLOYEELOOKUPSERVICE_EXCEPTION = e;
    }

    public EmployeeLookupService_Service() {
        super(__getWsdlLocation(), EMPLOYEELOOKUPSERVICE_QNAME);
    }

    public EmployeeLookupService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEELOOKUPSERVICE_QNAME, features);
    }

    public EmployeeLookupService_Service(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEELOOKUPSERVICE_QNAME);
    }

    public EmployeeLookupService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEELOOKUPSERVICE_QNAME, features);
    }

    public EmployeeLookupService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeLookupService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeLookupService
     */
    @WebEndpoint(name = "employeeLookupPort")
    public EmployeeLookupService getEmployeeLookupPort() {
        return super.getPort(new QName("http://www.memorylack.com/company", "employeeLookupPort"), EmployeeLookupService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeLookupService
     */
    @WebEndpoint(name = "employeeLookupPort")
    public EmployeeLookupService getEmployeeLookupPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.memorylack.com/company", "employeeLookupPort"), EmployeeLookupService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEELOOKUPSERVICE_EXCEPTION!= null) {
            throw EMPLOYEELOOKUPSERVICE_EXCEPTION;
        }
        return EMPLOYEELOOKUPSERVICE_WSDL_LOCATION;
    }


}
